# Gitee CI/CD 配置文件
# 用于自动构建 Android APK

stages:
  - build
  - deploy

variables:
  # Android SDK 版本
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"

# 构建 Debug APK
build_debug:
  stage: build
  image: openjdk:11-jdk
  before_script:
    - echo "开始构建 Debug APK"
    - chmod +x gradlew
    # 配置 Android SDK（如果需要）
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  script:
    - echo "执行 Gradle 构建..."
    - ./gradlew clean
    - ./gradlew assembleDebug
    - echo "构建完成"
  artifacts:
    name: "debug-apk-$CI_COMMIT_SHORT_SHA"
    paths:
      - app/build/outputs/apk/debug/*.apk
    expire_in: 7 days
  only:
    - develop
    - feature/*
  tags:
    - android

# 构建 Release APK
build_release:
  stage: build
  image: openjdk:11-jdk
  before_script:
    - echo "开始构建 Release APK"
    - chmod +x gradlew
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    # 配置签名（从 Gitee CI/CD 环境变量中获取）
    - |
      if [ ! -z "$KEYSTORE_FILE" ]; then
        echo $KEYSTORE_FILE | base64 -d > keystore.jks
        export KEYSTORE_PATH=$PWD/keystore.jks
      fi
  script:
    - echo "执行 Gradle 构建..."
    - ./gradlew clean
    - |
      if [ ! -z "$KEYSTORE_PATH" ]; then
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD
      else
        ./gradlew assembleRelease
      fi
    - echo "构建完成"
    # 重命名 APK 文件，包含版本信息
    - |
      VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"')
      VERSION_CODE=$(git rev-list --count HEAD)
      mv app/build/outputs/apk/release/app-release.apk \
         app/build/outputs/apk/release/MeetingMinutes-v${VERSION_NAME}-${VERSION_CODE}.apk
  artifacts:
    name: "release-apk-v$CI_COMMIT_TAG"
    paths:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/mapping/release/mapping.txt
    expire_in: 30 days
  only:
    - master
    - tags
  tags:
    - android

# 运行单元测试
test:
  stage: build
  image: openjdk:11-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
  artifacts:
    reports:
      junit: app/build/test-results/test/**/TEST-*.xml
    paths:
      - app/build/reports/tests/
      - app/build/reports/jacoco/
  only:
    - merge_requests
    - develop
  tags:
    - android

# 部署到测试环境（可选）
deploy_beta:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "部署到测试环境..."
    # 上传到蒲公英
    - |
      if [ ! -z "$PGYER_API_KEY" ]; then
        curl -F "file=@app/build/outputs/apk/release/*.apk" \
             -F "_api_key=$PGYER_API_KEY" \
             -F "buildInstallType=2" \
             -F "buildPassword=$PGYER_PASSWORD" \
             https://www.pgyer.com/apiv2/app/upload
      fi
    # 或上传到 fir.im
    - |
      if [ ! -z "$FIR_API_TOKEN" ]; then
        curl -F "file=@app/build/outputs/apk/release/*.apk" \
             -F "token=$FIR_API_TOKEN" \
             https://upload.fir.im/api/v2/app
      fi
  dependencies:
    - build_release
  only:
    - master
  when: manual
  tags:
    - deploy

# 发布到生产环境
deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl git
  script:
    - echo "发布到生产环境..."
    # 创建版本信息 JSON
    - |
      VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"')
      VERSION_CODE=$(git rev-list --count HEAD)
      APK_FILE=$(ls app/build/outputs/apk/release/*.apk)
      APK_SIZE=$(stat -c%s "$APK_FILE")
      
      cat > version.json <<EOF
      {
        "versionName": "$VERSION_NAME",
        "versionCode": $VERSION_CODE,
        "downloadUrl": "https://gitee.com/$CI_PROJECT_PATH/releases/download/$CI_COMMIT_TAG/$(basename $APK_FILE)",
        "updateLog": "$(git tag -l --format='%(contents)' $CI_COMMIT_TAG)",
        "forceUpdate": false,
        "fileSize": $APK_SIZE,
        "md5": "$(md5sum $APK_FILE | awk '{print $1}')"
      }
      EOF
    
    # 上传版本信息到服务器
    - |
      if [ ! -z "$DEPLOY_SERVER" ]; then
        curl -X POST "$DEPLOY_SERVER/api/version/update" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $DEPLOY_TOKEN" \
             -d @version.json
      fi
    
    - echo "发布完成"
  dependencies:
    - build_release
  only:
    - tags
  when: manual
  tags:
    - deploy

# 清理旧的构建产物
cleanup:
  stage: deploy
  image: alpine:latest
  script:
    - echo "清理完成"
  when: always
  tags:
    - cleanup

